services:
  app:
    image: ghcr.io/ame180/drm-app:latest
    build:
      context: .
      dockerfile: infrastructure/Dockerfile-prod
      target: prod
    volumes:
      - ./db.sqlite:/app/db.sqlite
      - ./.env:/app/.env
    env_file: .env
    entrypoint: ./entrypoint.sh
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}