services:
  php:
    image: ghcr.io/ame180/drm-app:latest
    build:
      context: .
      dockerfile: infrastructure/Dockerfile-prod
      target: prod
    volumes:
      - ./.env:/app/.env
      - assets:/app/public
    env_file: .env
    entrypoint: ./entrypoint.sh
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: ghcr.io/ame180/nginx-php:latest
    environment:
      APP_PATH: /app
      VIRTUAL_HOST: ${APP_HOST}
      LETSENCRYPT_HOST: ${APP_HOST}
    volumes:
      - assets:/app/public
    expose:
      - 80
    depends_on:
      - php

  mysql:
    image: ghcr.io/ame180/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
  assets: