services:
  php:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile-prod
      target: dev
    volumes:
      - .:/app
    env_file: .env
    entrypoint: infrastructure/entrypoint-prod.sh
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: ghcr.io/ame180/nginx-php:latest
    environment:
      APP_PATH: /app
    volumes:
      - .:/app
    ports:
      - "80:80"
    depends_on:
      - php

  mysql:
    image: ghcr.io/ame180/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: