services:
  app:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile-prod
      target: dev
    volumes:
      - .:/app
    env_file: .env
    entrypoint: infrastructure/entrypoint-prod.sh
    ports:
      - ${APP_PORT}:80