services:
  app:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
      target: dev
    volumes:
      - .:/app
    env_file: .env
    entrypoint: infrastructure/entrypoint.sh
    ports:
      - ${APP_PORT}:80