services:
  app:
    image: ghcr.io/ame180/drm-app:latest
    build:
      context: .
      dockerfile: infrastructure/Dockerfile-prod
      target: prod
    volumes:
      - ./.env:/app/.env
    env_file: .env
    entrypoint: ./entrypoint.sh
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=${APP_HOST}
      - LETSENCRYPT_HOST=${APP_HOST}
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: ghcr.io/ame180/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    expose:
      - "3306"
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: