services:
  app:
    build:
      context: .
      dockerfile: infrastructure/Dockerfile
    volumes:
      - .:${APP_PATH}
    working_dir: ${APP_PATH}
    env_file: .env
    entrypoint: infrastructure/entrypoint.sh
    ports:
      - ${APP_PORT}:80