services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/app
    working_dir: /var/www/app
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/app/public
    ports:
      - "80:80"